
repos:
  - repo: local
    hooks:
      - id: black
        name: Format with Black
        entry: poetry run black
        language: system
        types: [python]

      - id: ruff
        name: Check with Ruff
        entry: poetry run ruff
        language: system
        pass_filenames: false
        always_run: true
        args: ["check", ".", "--fix"]

      - id: mypy
        name: Validate types with MyPy
        entry: poetry run mypy
        language: system
        types: [python]
        pass_filenames: false
        args:
          - "."