app_name = "My Self-Hosted Drive"
debug = true
storage_type = "local"

[local_storage]
base_path = "/home/json/PycharmProjects/put/static"

[s3_storage]
bucket_name = "my-s3-bucket"
region_name = "us-west-2"
access_key_id = "YOUR_ACCESS_KEY"
secret_access_key = "YOUR_SECRET_KEY"

[tus]
max_size = 2147483648  # 2GB
expiration_period = 86400  # 24 hours

[api]
prefix = "/api"
cors_origins = ["http://localhost:3000", "https://example.com"]
cors_headers = ["*"]

[logging]
level = "INFO"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"